artifacts:
  registry: us-docker.pkg.dev/techolution-public
  repository: appmod-pa-demo

deployments:
  egpt-react-fe:
    replicas: 1
    labels:
      app: egpt-react-fe
    imageTag: latest
    imagePullPolicy: Always
    containerPort: 3000
    envParameters:
      TEST_ENV: one
      TEMP_ENV: two
    resources:
      resourceLimits:
        cpu: 500m
        memory: 2000Mi
      resourceRequests:
        cpu: 250m
        memory: 2000Mi
    serviceName: egpt-react-fe
    serviceType: ClusterIP
    servicePort: 80
    serviceTargetPort: 3000