{{- range $name, $cfg := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    maintainer: "DevOps Team"
    lastUpdated: {{ $.Values.lastUpdatedDate | quote }}
type: Opaque
data:
  {{- range $key, $value := $cfg.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
---
{{- end }}